Repository etcd-io/etcd-operator, pull requests merged in 2024-10, with the labels that each got.

#3 Add operator survey to repo
  wg/survey/2024-operator-survey.md
  wg/survey/hard_part.png
  wg/survey/manage.png
  wg/survey/no_clusters.png
  wg/survey/run_method.png
  wg/survey/where_use.png
Labels: approved, size/L

#4 Move wg/survey into docs
  docs/wg/survey/2024-operator-survey.md
  docs/wg/survey/hard_part.png
  docs/wg/survey/manage.png
  docs/wg/survey/no_clusters.png
  docs/wg/survey/run_method.png
  docs/wg/survey/where_use.png
Labels: approved, lgtm, size/XS

#5 Add operator evaluation
  docs/wg/evaluation/evaluation.pdf
Labels: approved, size/XS
