Repository etcd-io/etcd-operator, pull requests merged in 2025-01, with the labels that each got.

#20 Add Dependabot config for weekly updates
  .github/dependabot.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  Dockerfile
Labels: approved, size/M

#17 Initial implementation for the Reconcile Logic
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/etcdcluster_controller.go
  internal/controller/utils.go
  internal/controller/utils_test.go
  internal/etcdutils/etcdutils.go
  internal/etcdutils/etcdutils_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
Labels: approved, size/XXL, ok-to-test

#25 Some minor enhancement & cleanup on the reconcile process
  internal/controller/etcdcluster_controller.go
Labels: approved, size/M

#24 feat: Add a workflow to guarantee that the import items are properly grouped and ordered
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  tools/mod/doc.go
  tools/mod/go.mod
  tools/mod/go.sum
  tools/mod/tools.go
Labels: approved, size/XXL, ok-to-test

#35 Chore: Fix lint error
  internal/controller/etcdcluster_controller.go
  internal/controller/utils.go
  internal/controller/utils_test.go
  internal/etcdutils/etcdutils.go
  internal/etcdutils/etcdutils_test.go
  test/e2e/e2e_test.go
Labels: approved, size/M, ok-to-test

#36 Add tool/mod into dependabot.yml and group bumping go.etcd.io/* dependencies
  .github/dependabot.yml
Labels: approved, size/S

#39 Align Dockerfile builder image
  Dockerfile
Labels: approved, size/XS

#42 Update golang toolchain to 1.23.5
  Dockerfile
  go.mod
  tools/mod/go.mod
Labels: approved, size/XS, ok-to-test

#45 github workflow: enable workflow approval
  .github/workflows/gh-workflow-approve.yml
Labels: approved, size/M, ok-to-test

#40 Chore: Manage tool versions at tools/mod
  Makefile
  tools/mod/go.mod
  tools/mod/go.sum
  tools/mod/tools.go
Labels: approved, ok-to-test, size/XL

#58 Remove lint, test and test-e2e GitHub workflows
  .github/workflows/lint.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: approved, size/M

#57 Add reconciliation workflow diagram
  docs/design/reconcile_loop_v0.1.0.png
  docs/design/reconcile_loop_v0.1.0.uxf
Labels: approved, lgtm, size/XXL

#59 Add the initial scaffold of certificate management
  pkg/certificate/auto/doc.go
  pkg/certificate/cert-manager/doc.go
  pkg/certificate/interface.go
Labels: approved, size/L
