Repository etcd-io/etcd-operator, pull requests merged in 2025-09, with the labels that each got.

#198 upgrade lint to v2
  .golangci.yml
  cmd/main.go
  internal/controller/suite_test.go
  pkg/certificate/cert_manager/provider.go
  test/e2e/cert_manager_test.go
  test/e2e/e2e_test.go
  test/utils/utils.go
  tools/mod/go.mod
Labels: approved, size/M

#205 Set `GOTOOLCHAIN` environment variable
  Makefile
Labels: approved, size/S

#176 feat: support Pod's annotations and labels for EtcdCluster
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.etcd.io_etcdclusters.yaml
  docs/api-references/docs.md
  internal/controller/utils.go
  internal/controller/utils_test.go
Labels: approved, size/L, ok-to-test

#212 add go mod tidy check
  Makefile
Labels: approved, size/S

#192 test(e2e): add scaling & KV functionality tests; extract shared helpers
  test/e2e/e2e_test.go
  test/e2e/helpers_test.go
Labels: approved, ok-to-test, size/XL
