Repository etcd-io/etcd-operator, pull requests merged in 2025-03, with the labels that each got.

#85 Update dev container to Go 1.24
  .devcontainer/devcontainer.json
Labels: approved, size/XS, ok-to-test

#88 Print more detailed log when running unit test
  Makefile
Labels: approved, lgtm, size/XS

#84 Remove usage of ginkgo entirely
  .golangci.yml
  Makefile
  go.mod
  go.sum
  internal/controller/etcdcluster_controller_test.go
  internal/controller/suite_test.go
  internal/controller/utils_test.go
Labels: approved, size/L, ok-to-test

#96 chore: bump golang to 1.24.1
  Dockerfile
  README.md
  go.mod
  tools/mod/go.mod
Labels: approved, size/XS, ok-to-test

#100 Add release script
  Makefile
  scripts/release.sh
Labels: approved, size/M

#109 Defaults to ReadWriteOnce when it's empty or not provided
  internal/controller/utils.go
Labels: approved, size/XS

#110 Update Roadmap for v0.1.0 release
  docs/roadmap.md
Labels: approved, size/XS

#117 Add installation documentation
  docs/install.md
Labels: approved, size/L
