Repository etcd-io/etcd-operator, pull requests merged in 2025-02, with the labels that each got.

#63 Update golang toolchain to version 1.23.6
  Dockerfile
  go.mod
  tools/mod/go.mod
Labels: approved, size/XS, ok-to-test

#66 Move certificate interface into dedicated package to avoid cycle dependency
  pkg/certificate/certificate.go
  pkg/certificate/interfaces/interface.go
Labels: approved, size/M

#62 Convert existing e2e tests from Gingko to e2e framework
  Makefile
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: approved, ok-to-test, size/XL

#70 Bump golangci-lint from v1.63.4 to v1.64.5
  .golangci.yml
  tools/mod/go.mod
  tools/mod/go.sum
Labels: approved, size/L

#72 Remove unnecessary make command to install tools in e2e tests
  test/e2e/e2e_suite_test.go
Labels: approved, size/S

#73 Remove make manifests from e2e tests
  Makefile
  test/e2e/e2e_suite_test.go
Labels: approved, size/S

#67 cleanup: refactor code with wait.ExponentialBackoffWithContext
  internal/controller/utils.go
  internal/controller/utils_test.go
Labels: approved, size/M, ok-to-test

#76 Add ‘kind’ to pinned tool dependencies and ensure it’s on PATH for E2e tests
  Makefile
  tools/mod/go.mod
  tools/mod/go.sum
  tools/mod/tools.go
Labels: approved, size/S, ok-to-test

#79 Remove gingko from test/utils
  test/utils/utils.go
Labels: approved, size/XS, ok-to-test

#81 Add ivanvc as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#82 Update golangci-lint installation to use installation script
  Makefile
Labels: approved, size/XS

#71 Bump go to 1.24.0
  Dockerfile
  README.md
  go.mod
  tools/mod/go.mod
Labels: approved, size/S

#44 Support data persistence: integrate with storageClass
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.etcd.io_etcdclusters.yaml
  internal/controller/utils.go
Labels: approved, size/L, ok-to-test

#83 Add certificate management user interface
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.etcd.io_etcdclusters.yaml
Labels: approved, size/L
