Repository etcd-io/etcd-operator, pull requests merged in 2025-04, with the labels that each got.

#124 dependency: bump etcd group from v3.5.17 to v3.5.21
  go.mod
  go.sum
Labels: approved, size/M

#129 Bump go toolchain to v1.24.2
  Dockerfile
  go.mod
  tools/mod/go.mod
Labels: approved, size/XS, ok-to-test

#108 Add e2e tests for Data Persistence
  test/e2e/datapersistence_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: approved, size/L

#123 add e2e podman config
  Makefile
  config/manager/kustomization.yaml
  test/e2e/e2e_suite_test.go
  test/utils/utils.go
Labels: approved, size/M, ok-to-test
