Repository etcd-io/etcd-operator, pull requests merged in 2025-06, with the labels that each got.

#162 chore: use Go usetesting
  internal/controller/utils_test.go
  internal/etcdutils/etcdutils_test.go
Labels: approved, size/S

#163 chore: enable usetesting linter directive
  .golangci.yml
Labels: size/XS

#164 Bump Go to 1.24.4
  Dockerfile
  go.mod
  tools/mod/go.mod
Labels: approved, size/XS, ok-to-test

#166 chore(CI): add gci formatter
  .golangci.yml
  internal/controller/utils.go
  test/e2e/datapersistence_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: approved, size/M

#141 Add `CertManager` interface functions
  config/samples/certificateProvider/cert_manager_selfsigned_issuer.yaml
  go.mod
  go.sum
  pkg/certificate/cert_manager/doc.go
  pkg/certificate/cert_manager/provider.go
  pkg/certificate/certificate.go
  pkg/certificate/interfaces/interface.go
  test/e2e/cert_manager_test.go
Labels: approved, size/XL
